<?php

namespace iTRON\PollyTTS;

use iTRON\WP_Lock\WP_Lock;

/**
 * Class providers logic responsible for connecting with Amazon Polly Service
 * and converting post text to audio.
 *
 * @since      0.1
 *
 */

class PollyService {
	const GENERATE_POST_AUDIO_TASK = 'generate_post_audio';
	const NONCE_NAME               = 'itron-polly-tts-post-nonce';
	const LOCK_PREFIX              = 'itron-polly-tts-generate-audio-file:';

	/**
	 * @var Common
	 */
	private $common;

	/**
	 * PollyService constructor.
	 *
	 * @param Common $common
	 */
	public function __construct( Common $common) {
		$this->common = $common;
	}

	/**
	 * Important. Run whenever new post is being created (or updated). The method generates a background task to generate the audio file.
	 *
	 * @since      0.1
	 */
	public function save_post( $post_id, $post, $updated ) {
		static $single_run = 0;

		if ( $single_run++ ) {
			return;
		}

		$common = $this->common;
		$logger = new Logger();
		$logger->log( sprintf( '%s Saving post ( id=%s )', __METHOD__, $post_id ) );

		// Check if this isn't an auto save.
		if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
			return;
		}

		// Check to make sure this is not a new post creation.
		if ( ! $updated ) {
			return;
		}

		// Validate if this post which is being saved is one of supported types. If not, return.
		$post_types_supported = $common->get_posttypes_array();
		$post_type            = get_post_type( $post_id );
		if ( ! in_array( $post_type, $post_types_supported ) ) {
			return;
		}

		// If nonce is valid then update post meta
		// If it's not valid then this is probably a quick or bulk edit request in which case we won't update the polly post meta
		if ( isset( $_POST[ self::NONCE_NAME ] ) && wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST[ self::NONCE_NAME ] ) ), 'itron-polly-tts' ) ) {
			update_post_meta( $post_id, 'itron_polly_tts_enable', (int) isset( $_POST['itron_polly_tts_enable'] ) );

			if ( $common->is_post_voice_override_disabled() ) {
				delete_post_meta( $post_id, 'itron_polly_tts_voice_id' );
			} elseif ( isset( $_POST['itron_polly_tts_voice_id'] ) ) {
				// Update post voice ID
				$voice_id = sanitize_text_field( wp_unslash( $_POST['itron_polly_tts_voice_id'] ) );
				try {
					$voice_id = $common->resolve_polly_voice_id(
						$common->get_post_source_language( $post_id ),
						$voice_id,
						$common->get_voice_id()
					);
				} catch ( \Exception $e ) {
					$logger->log( sprintf( '%s Unable to validate selected voice while saving post ( id=%s ): %s', __METHOD__, $post_id, $e->getMessage() ) );
				}
				update_post_meta( $post_id, 'itron_polly_tts_voice_id', $voice_id );
			}
		}

		if ( ! ( wp_is_post_revision( $post_id ) || wp_is_post_autosave( $post_id ) ) ) {
			$logger->log( sprintf( '%s Starting background task process ( id=%s )', __METHOD__, $post_id ) );
			$background_task = new BackgroundTask();
			$background_task->queue_audio( $post_id );
		}
	}

	/**
	 * Important. Executes the Amazon Polly API to create audio file and save to the configured storage location
	 *
	 * @throws ConcurrentAudioGenerationException
	 * @since      0.1
	 */
	public function generate_audio( $post_id ) {
		$logger = new Logger();
		$common = $this->common;
		$logger->log( sprintf( '%s Generating audio for post ( id=%s )', __METHOD__, $post_id ) );

		// The generate audio file lock is to prevent multiple processes from generating audio for the same post.
		$lock    = new WP_Lock( self::LOCK_PREFIX . $post_id );
		$allowed = $lock->acquire( WP_Lock::WRITE, false, 300 );

		/**
		 * Fires before attempting to generate and save the Amazon Polly audio files.
		 * This hook can be used to prevent the audio files from being generated.
		 *
		 * @param int $post_id The post id to generate audio files for.
		 * @param bool $continue Whether to continue with generating the audio files. Default true.
		 * @param bool $allowed Whether the audio generation is allowed for the post now.
		 */
		$continue = true;
		do_action_ref_array( 'itron_polly_tts_pre_generate_audio', array( $post_id, &$continue, $allowed ) );

		if ( ! $continue ) {
			$allowed && $lock->release();
			$logger->log( sprintf( '%s Skipping audio generation for post ( id=%s )', __METHOD__, $post_id ) );
			return;
		}

		if ( ! $allowed ) {
			// Another process is already generating audio for this post.
			do_action( 'itron_polly_tts_post_generate_audio_locked', $post_id );
			$logger->log( sprintf( '%s Audio is already being generated by another process. Skipping audio generating for the post ( id=%s )', __METHOD__, $post_id ) );
			throw new ConcurrentAudioGenerationException();
		}

		$is_key_valid = (bool) get_option( 'itron_polly_tts_valid_keys' );
		if ( ! $is_key_valid ) {
			$is_key_valid = $common->validate_itron_polly_tts_access( true, false );
		}
		if ( ! $is_key_valid ) {
			if ( ! $common->has_post_audio( $post_id ) ) {
				$common->set_post_audio_state( $post_id, Common::AUDIO_STATE_ERROR );
			}
			$lock->release();
			$logger->log( sprintf( '%s AWS keys are not valid. Skipping audio generation for post ( id=%s )', __METHOD__, $post_id ) );
			return;
		}

		$is_polly_enabled = (bool) get_post_meta( $post_id, 'itron_polly_tts_enable', true );
		$voice_id         = get_post_meta( $post_id, 'itron_polly_tts_voice_id', true );
		$source_language  = $common->get_post_source_language( $post_id );

		try {
			if ( $is_polly_enabled ) {
				if ( ! $common->has_post_audio( $post_id ) ) {
					$common->set_post_audio_state( $post_id, Common::AUDIO_STATE_RUNNING );
				}

				if ( $common->is_post_voice_override_disabled() && ! empty( $voice_id ) ) {
					$logger->log( sprintf( '%s Removing per-post voice override because post voice overrides are disabled ( id=%s voice=%s )', __METHOD__, $post_id, $voice_id ) );
					delete_post_meta( $post_id, 'itron_polly_tts_voice_id' );
					$voice_id = '';
				}

				$resolved_voice_id = $common->resolve_polly_voice_id(
					$source_language,
					$voice_id,
					$common->get_voice_id()
				);

				if ( $resolved_voice_id !== $voice_id ) {
					$logger->log(
						sprintf(
							'%s Voice adjusted for post ( id=%s ): requested=%s resolved=%s language=%s',
							__METHOD__,
							$post_id,
							'' !== $voice_id ? $voice_id : '[empty]',
							'' !== $resolved_voice_id ? $resolved_voice_id : '[empty]',
							$source_language
						)
					);
					if ( $common->is_post_voice_override_disabled() ) {
						delete_post_meta( $post_id, 'itron_polly_tts_voice_id' );
					} else {
						update_post_meta( $post_id, 'itron_polly_tts_voice_id', $resolved_voice_id );
					}
				}

				$voice_id = $resolved_voice_id;
				if ( empty( $voice_id ) ) {
					throw new \Exception( 'No supported Amazon Polly voices are available for this post language in the selected AWS region.' );
				}

				$stored_audio_location  = (string) get_post_meta( $post_id, 'itron_polly_tts_audio_location', true );
				$current_audio_location = $common->get_file_handler()->get_type();
				if ( '' !== $stored_audio_location && $stored_audio_location !== $current_audio_location ) {
					$logger->log(
						sprintf(
							'%s Storage changed for post ( id=%s ): stored=%s current=%s. Removing stale audio before regeneration.',
							__METHOD__,
							$post_id,
							$stored_audio_location,
							$current_audio_location
						)
					);
					$common->delete_post_audio( $post_id );
					$common->set_post_audio_state( $post_id, Common::AUDIO_STATE_RUNNING );
				}

				$audio_hash   = get_post_meta( $post_id, 'itron_polly_tts_audio_hash', true );
				$current_hash = $common->get_audio_hash( $post_id );

				// If the hash is the same, we don't need to regenerate the audio.
				if ( $audio_hash === $current_hash && $common->has_post_audio( $post_id ) ) {
					do_action( 'itron_polly_tts_post_identical_audio', $post_id, $audio_hash );
					$common->set_post_audio_state( $post_id, Common::AUDIO_STATE_READY );
					throw new IdenticalAudioException();
				}

				do_action( 'itron_polly_tts_post_generate_audio_validated', $post_id );

				$logger->log( sprintf( '%s Basic validation OK', __METHOD__ ) );

				// Sammple Rate
				$sample_rate = $common->get_sample_rate();

				// Cleaning text. Includes for example removing not supported characters etc.
				$clean_text = $common->clean_text( $post_id, true, false );

				$logger->log( sprintf( '%s <<< Clean Text >>> ', __METHOD__ ) );
				$logger->log( sprintf( '%s', $clean_text ) );
				$logger->log( sprintf( '%s __________', __METHOD__ ) );

				// Breaking text into smaller parts, which will be then send to Amazon Polly for conversion.
				$sentences = $common->break_text( $clean_text );

				// We will be operating on local file system for stiching files together.
				$wp_filesystem = $common->prepare_wp_filesystem();

				// Actual invocation of method which will call Amazon Polly API and create audio file.
				$this->convert_to_audio( $post_id, $sample_rate, $voice_id, $sentences, $wp_filesystem, '' );

				update_post_meta( $post_id, 'itron_polly_tts_audio_hash', $current_hash );

				// Checking what was the source language of text and updating options for translate operations.
				update_post_meta( $post_id, 'itron_polly_tts_transcript_' . $source_language, $clean_text );
				update_post_meta( $post_id, 'itron_polly_tts_transcript_source_lan', $source_language );
				$common->set_post_audio_state( $post_id, Common::AUDIO_STATE_READY );

				// update_post_meta() invalidates post meta caches, but it does not flush post query caches.
				// Hosted environments with persistent object cache can otherwise keep stale admin list results
				// for filters like "Without audio" even after the final audio link has been saved.
				clean_post_cache( $post_id );
			} else { // Remove audio files and post meta (if existing) if Polly is not enabled
				// @todo: Don't delete audio files when Polly is disabled for the post.
				$common->delete_post_audio( $post_id );
			}

			/**
			 * Fires after attempting to generate and save the Amazon Polly audio files
			 *
			 * @param int $post_id The post id to generate audio files for
			 */
			do_action( 'itron_polly_tts_post_generate_audio', $post_id, $is_polly_enabled );
		} catch ( \Throwable $e ) {
			if ( ! $common->has_post_audio( $post_id ) ) {
				$common->set_post_audio_state( $post_id, Common::AUDIO_STATE_ERROR );
			}
			$logger->log( sprintf( '%s Error: %s', __METHOD__, $e->getMessage() ) );
		} finally {
			$lock->release();
		}
	}
	/*
	private function start_speech_synthesis_task($common, $post_id, $sample_rate, $voice_id, $sentences, $lang) {

		$full_text = '';

		// Iterating through each of text parts.
		foreach ( $sentences as $key => $text_content ) {

			// Remove all tags
			$text_content = strip_tags($text_content);

			// If plugin SSML support option is enabled, plugin will try to decode all SSML tags.
			$text_content = $this->ssml_support($common, $text_content);

			$full_text = $full_text . $text_content;

		}


		// Adding breaths sounds (if enabled).
		$full_text = $this->add_breaths($common, $full_text);

		// Adding special polly mark.
		$full_text = $this->add_mark_tag($common, $full_text);

		// Adding speak polly mark.
		$full_text = $this->add_speak_tags($common, $full_text);

		//Preparing Amazon Polly client object.
		$polly_client = $common->get_polly_client();

		$s3_prefix = 'asyn/';
		if ( get_option('uploads_use_yearmonth_folders') ) {
			 $s3_prefix .= get_the_date( 'Y', $post_id ) . '/' . get_the_date( 'm', $post_id ) . "/";
		}

		$file_name = 'itron_polly_tts_' . $post_id . $lang . '.mp3';

		//Preparing lexicons which will be used create audio.
		$lexicons       = $common->get_lexicons();
		$lexicons_array = explode( ' ', $lexicons );


		//Call Amazon Polly service.
		if ( ! empty( $lexicons ) and ( count( $lexicons_array ) > 0 ) ) {

			$result = $polly_client->startSpeechSynthesisTask(
				array(
					'OutputFormat' => 'mp3',
					'SampleRate'   => $sample_rate,
					'Text'         => $full_text,
					'TextType'     => 'ssml',
					'VoiceId'      => $voice_id,
					'OutputS3BucketName' => $common->get_s3_bucket_name(),
					'OutputS3KeyPrefix' => $s3_prefix . $file_name,
					'LexiconNames' => $lexicons_array,
				)
			);

		} else {

			$result = $polly_client->startSpeechSynthesisTask(
				array(
					'OutputFormat' => 'mp3',
					'SampleRate'   => $sample_rate,
					'Text'         => $full_text,
					'TextType'     => 'ssml',
					'VoiceId'      => $voice_id,
					'OutputS3BucketName' => $common->get_s3_bucket_name(),
					'OutputS3KeyPrefix' => $s3_prefix . $file_name
				)
			);

		}

		// Saving audio file in final destination.
		$audio_location_link = $common->get_s3_object_link($common, $post_id, $file_name);

		// This will bust the browser cache when a content revision is made.
		$audio_location_link = add_query_arg( 'version', time(), $audio_location_link );

		// We are using a hash of these values to improve the speed of queries.
		$itron_polly_tts_settings_hash = md5( $voice_id . $sample_rate . "s3" );

		if ( $lang == '' ) {
			update_post_meta( $post_id, 'itron_polly_tts_audio_link_location', $audio_location_link );
			update_post_meta( $post_id, 'itron_polly_tts_audio_location', "s3" );
			update_post_meta( $post_id, 'itron_polly_tts_generated_voice_id', $voice_id );
		} else {
			update_post_meta( $post_id, 'itron_polly_tts_translation_' . $lang, '1' );
		}

		// Update post meta data.
		update_post_meta( $post_id, 'itron_polly_tts_enable', 1 );
		update_post_meta( $post_id, 'itron_polly_tts_voice_id', $voice_id );
		update_post_meta( $post_id, 'itron_polly_tts_sample_rate', $sample_rate );
		update_post_meta( $post_id, 'itron_polly_tts_settings_hash', $itron_polly_tts_settings_hash );


	}
	*/

	/**
	 * Method execute Amazon Polly API and convert content which was provided to audio file.
	 *
	 * @param           string $post_id                 ID of the posts which is being converted.
	 * @param           string $sample_rate         Sample rate for speech conversion.
	 * @param           string $voice_id                Amazon Polly voice ID.
	 * @param           string $sentences               Sentences which should be converted to audio.
	 * @param           string $wp_filesystem       Reference to WP File system variable.
	 * @param           string $lang       Language
	 * @since      0.1
	 */
	public function convert_to_audio( $post_id, $sample_rate, $voice_id, $sentences, $wp_filesystem, $lang ) {

		$logger = new Logger();
		$logger->log( sprintf( '%s Converting to Audio', __METHOD__ ) );

		// Creating new standard common object for interacting with other methods of the plugin.
		$common = $this->common;

		// Translation support was removed from the plugin, so this branch only matters
		// for legacy flows that still pass a target language explicitly.
		if ( ! empty( $lang ) ) {
			foreach ( $common->get_all_polly_languages() as $language_code ) {
				if ( $language_code === $lang ) {
					$voice_id = $common->get_resolved_polly_voice_option( 'itron_polly_tts_trans_langs_' . $language_code . '_voice', $language_code, $voice_id );
				}
			}
		}

		$voice_language    = empty( $lang ) ? $common->get_post_source_language( $post_id ) : $lang;
		$resolved_voice_id = $common->resolve_polly_voice_id( $voice_language, $voice_id );

		if ( $resolved_voice_id !== $voice_id ) {
			$logger->log(
				sprintf(
					'%s Voice adjusted before synthesis: requested=%s resolved=%s language=%s post_id=%s',
					__METHOD__,
					'' !== $voice_id ? $voice_id : '[empty]',
					'' !== $resolved_voice_id ? $resolved_voice_id : '[empty]',
					$voice_language,
					$post_id
				)
			);

			if ( empty( $lang ) ) {
				if ( $common->is_post_voice_override_disabled() ) {
					delete_post_meta( $post_id, 'itron_polly_tts_voice_id' );
				} else {
					update_post_meta( $post_id, 'itron_polly_tts_voice_id', $resolved_voice_id );
				}
			}
		}

		$voice_id = $resolved_voice_id;

		if ( empty( $voice_id ) ) {
			$logger->log( sprintf( '%s No supported voice available for language %s. Skipping audio generation.', __METHOD__, $voice_language ) );
			return;
		}

		// Just in case we check if sample rate is valid, if not we will set default value.
		$sample_rate_values = array( '24000', '22050', '16000', '8000' );
		if ( ! in_array( $sample_rate, $sample_rate_values, true ) ) {
			$sample_rate = '24000';
		}

		// In case of asynchronous synthesis flow.
		//$itron_polly_tts_asynchronous = apply_filters( '$itron_polly_tts_asynchronous', '' );
		//if ( $itron_polly_tts_asynchronous ) {
		//	$this->start_speech_synthesis_task($common, $post_id, $sample_rate, $voice_id, $sentences, $lang);
		//	return;
		//}

		// Preparing locations and names of temporary files which will be used.
		$random              = wp_rand( 5, 10 );
		$upload_dir          = wp_upload_dir()['basedir'];
		$file_prefix         = 'itron_polly_tts_';
		$file_name           = $file_prefix . $post_id . $lang . '.mp3';
		$file_temp_full_name = trailingslashit( $upload_dir ) . 'temp_' . $file_name . $random;
		$dir_final_full_name = trailingslashit( $upload_dir );
		if ( get_option( 'uploads_use_yearmonth_folders' ) ) {
			$dir_final_full_name .= get_the_date( 'Y', $post_id ) . '/' . get_the_date( 'm', $post_id ) . '/';
		}
		$file_final_full_name = $dir_final_full_name . $file_name;

		// Delete temporary file if already exists.
		if ( $wp_filesystem->exists( $file_temp_full_name ) ) {
			$wp_filesystem->delete( $file_temp_full_name );
		}
		// Delete final file if already exists.
		if ( $wp_filesystem->exists( $file_final_full_name ) ) {
			$wp_filesystem->delete( $file_final_full_name );
		}

		// We might be stiching multiple smaller audio files. This variable will
		// be used to detact the first part.
		$first_part = true;

		// Iterating through each of text parts.
		foreach ( $sentences as $key => $text_content ) {

			$logger->log( sprintf( '%s Part:', __METHOD__ ) );
			$logger->log( sprintf( '%s', $text_content ) );

			// Remove all tags
			$text_content = wp_strip_all_tags( $text_content, false );

			// Modify Speed
			$text_content = $common->modify_sentence_speed( $text_content );

			// Adding breaths sounds (if enabled).
			$text_content = $this->add_breaths( $common, $text_content );

			// If plugin SSML support option is enabled, plugin will try to decode all SSML tags.
			$text_content = $this->ssml_support( $common, $text_content );

			// Adding special polly mark.
			$text_content = $this->add_mark_tag( $common, $text_content );

			// Adding newscaster style tag
			$text_content = $this->add_newscaster_tag( $common, $text_content, $voice_id );

			// Adding conversational style tag
			$text_content = $this->add_conversational_tag( $common, $text_content, $voice_id );

			// Adding speak polly mark.
			$text_content = $this->add_speak_tags( $common, $text_content );

			//Preparing lexicons which will be used create audio.
			$lexicons       = $common->get_lexicons();
			$lexicons_array = explode( ' ', $lexicons );

			//Preparing Amazon Polly client object.
			$polly_client = $common->get_polly_client();

			//Detect Polly Engine (Standard / Neural).
			$engine               = $common->get_polly_engine( $voice_id );
			$news_style           = $common->should_news_style_be_used( $voice_id );
			$conversational_style = $common->should_conversational_style_be_used( $voice_id );

			$log  = sprintf( '%s Final Polly text:', __METHOD__ );
			$log .= sprintf( '%s', $text_content );
			$log .= sprintf( '%s Engine: %s ', __METHOD__, $engine );
			$log .= sprintf( '%s Voice: %s ', __METHOD__, $voice_id );
			$log .= sprintf( '%s SampleRate: %s ', __METHOD__, $sample_rate );
			$log .= sprintf( '%s News Style Enabled: %s ', __METHOD__, $news_style );
			$log .= sprintf( '%s Conversational Style Enabled: %s ', __METHOD__, $conversational_style );
			$logger->log( $log );

			//Call Amazon Polly service.
			if ( ! empty( $lexicons ) and ( count( $lexicons_array ) > 0 ) ) {
				$result = $polly_client->synthesizeSpeech(
					array(
						'Engine'       => $engine,
						'OutputFormat' => 'mp3',
						'SampleRate'   => $sample_rate,
						'Text'         => $text_content,
						'TextType'     => 'ssml',
						'VoiceId'      => $voice_id,
						'LexiconNames' => $lexicons_array,
					)
				);
			} else {

				$result = $polly_client->synthesizeSpeech(
					array(
						'Engine'       => $engine,
						'OutputFormat' => 'mp3',
						'SampleRate'   => $sample_rate,
						'Text'         => $text_content,
						'TextType'     => 'ssml',
						'VoiceId'      => $voice_id,
					)
				);
			}

			$logger->log( sprintf( '%s Audio returned from Polly', __METHOD__ ) );

			// Grab the stream and output to a file.
			$contents = $result['AudioStream']->getContents();

			// Save first part of the audio stream in the parial temporary file.
			$wp_filesystem->put_contents( $file_temp_full_name . '_part_' . $key, $contents );

			$logger->log( sprintf( '%s Part created ( %s )', __METHOD__, $file_temp_full_name . '_part_' . $key ) );

			// Merge new temporary file with previous ones.
			if ( $first_part ) {
				$wp_filesystem->put_contents( $file_temp_full_name, $contents );
				$first_part = false;
			} else {
				$common->remove_id3( $file_temp_full_name . '_part_' . $key, $wp_filesystem );
				$merged_file = $wp_filesystem->get_contents( $file_temp_full_name ) . $wp_filesystem->get_contents( $file_temp_full_name . '_part_' . $key );
				$wp_filesystem->put_contents( $file_temp_full_name, $merged_file );
			}

			// Deleting partial audio file.
			$wp_filesystem->delete( $file_temp_full_name . '_part_' . $key );

		}

		// Saving the duration of an audio file as the string 00:00.
		$playtime_string = $this->get_audio_playtime_string( $file_temp_full_name );
		if ( $playtime_string ) {
			update_post_meta( $post_id, 'itron_polly_tts_audio_playtime', $playtime_string );
		}

		// Saving audio file in final destination.
		$file_handler        = $common->get_file_handler();
		$audio_location_link = $file_handler->save( $wp_filesystem, $file_temp_full_name, $dir_final_full_name, $file_final_full_name, $post_id, $file_name );

		// This will bust the browser cache when a content revision is made.
		$audio_location_link = add_query_arg( 'version', time(), $audio_location_link );

		// We are using a hash of these values to improve the speed of queries.
		$itron_polly_tts_settings_hash = md5( $voice_id . $sample_rate . 's3' );

		if ( $lang == '' ) {
			update_post_meta( $post_id, 'itron_polly_tts_audio_link_location', $audio_location_link );
			update_post_meta( $post_id, 'itron_polly_tts_audio_location', $file_handler->get_type() );
			update_post_meta( $post_id, 'itron_polly_tts_generated_voice_id', $voice_id );
		} else {
			update_post_meta( $post_id, 'itron_polly_tts_translation_' . $lang, '1' );
		}

			// Update post meta data.
			update_post_meta( $post_id, 'itron_polly_tts_enable', 1 );
		if ( $common->is_post_voice_override_disabled() ) {
			delete_post_meta( $post_id, 'itron_polly_tts_voice_id' );
		} else {
			update_post_meta( $post_id, 'itron_polly_tts_voice_id', $voice_id );
		}
			update_post_meta( $post_id, 'itron_polly_tts_sample_rate', $sample_rate );
			update_post_meta( $post_id, 'itron_polly_tts_settings_hash', $itron_polly_tts_settings_hash );

		$logger->log( sprintf( '%s Final audio created!', __METHOD__ ) );

	}

	private function get_audio_playtime_string( string $file_path ): string {
		if ( ! function_exists( 'wp_read_audio_metadata' ) ) {
			require_once ABSPATH . 'wp-admin/includes/media.php';
		}

		if ( ! function_exists( 'wp_read_audio_metadata' ) ) {
			return '';
		}

		$metadata = wp_read_audio_metadata( $file_path );

		if ( ! is_array( $metadata ) || empty( $metadata['length_formatted'] ) ) {
			return '';
		}

		return (string) $metadata['length_formatted'];
	}

	/**
	 * Method add SSML breaths tags if functionality is enabled.
	 *
	 * @param           string $common                  Plugin common object.
	 * @param           string $text_content        Existing text.
	 * @since      0.1
	 */
	private function add_breaths( $common, $text_content) {
		// Depending on the plugin configuration SSML tags for automated breaths sound will be added.
		$is_breaths_enabled = $common->is_auto_breaths_enabled();
		if ( $is_breaths_enabled ) {
			$text_content = '<amazon:auto-breaths>' . $text_content . '</amazon:auto-breaths>';
		}

		return $text_content;
	}

	/**
	 * Method decode SSML tags  if functionality is enabled.
	 *
	 * @param           string $common                  Plugin common object.
	 * @param           string $text_content        Existing text.
	 * @since      0.1
	 */
	private function ssml_support( $common, $text_content) {
		// If plugin SSML support option is enabled, plugin will try to decode all SSML tags.
		$is_ssml_enabled = $common->is_ssml_enabled();
		if ( $is_ssml_enabled ) {
			$text_content = $common->decode_ssml_tags( $text_content );
		}

		$text_content = str_replace( '**AMAZONPOLLY*SSML*BREAK*time=***300ms***SSML**', '<break time="300ms"/>', $text_content );
		$text_content = str_replace( '**AMAZONPOLLY*SSML*BREAK*time=***500ms***SSML**', '<break time="500ms"/>', $text_content );
		$text_content = str_replace( '**AMAZONPOLLY*SSML*BREAK*time=***1s***SSML**', '<break time="500ms"/>', $text_content );

		return $text_content;
	}

	/**
	 * Method add special mark tag for output text.
	 *
	 * @param           string $common                  Plugin common object.
	 * @param           string $text_content        Existing text.
	 * @since      0.1
	 */
	private function add_mark_tag( $common, $text_content) {

		$itron_polly_tts_mark_value = 'wp-plugin-awslabs';
		$itron_polly_tts_mark_value = apply_filters( 'itron_polly_tts_mark_value', $itron_polly_tts_mark_value );

		$text_content = '<mark name="' . esc_attr( $itron_polly_tts_mark_value ) . '"/>' . $text_content . '';

		return $text_content;
	}

	private function add_newscaster_tag( $common, $text_content, $voice) {
		if ($common->should_news_style_be_used( $voice )) {
			$text_content = '<amazon:domain name="news">' . $text_content . '</amazon:domain>';
		}
		return $text_content;
	}

	private function add_conversational_tag( $common, $text_content, $voice) {
		if ($common->should_conversational_style_be_used( $voice )) {
			$text_content = '<amazon:domain name="conversational">' . $text_content . '</amazon:domain>';
		}
		return $text_content;
	}

	/**
	 * Method add speak tags for output text.
	 *
	 * @param           string $common                  Plugin common object.
	 * @param           string $text_content        Existing text.
	 * @since      0.1
	 */
	private function add_speak_tags( $common, $text_content) {

		$text_content = '<speak>' . $text_content . '</speak>';

		return $text_content;
	}


	/**
	 * Batch process the post transcriptions.
	 *
	 * @since      0.1
	 */
	public function ajax_bulk_synthesize() {
		check_ajax_referer( 'itron_polly_tts_ajax', 'nonce' );

		$batch_size                  = 1;
		$common                      = $this->common;
		$logger                      = new Logger();
		$post_types_supported        = $common->get_posttypes_array();
		$itron_polly_tts_voice_id       = $common->get_voice_id();
		$itron_polly_tts_sample_rate    = $common->get_sample_rate();
		$itron_polly_tts_audio_location = ( 'on' === get_option( 'itron_polly_tts_s3' ) ) ? 's3' : 'local';

		// We are using a hash of these values to improve the speed of queries.
		$itron_polly_tts_settings_hash = md5( $itron_polly_tts_voice_id . $itron_polly_tts_sample_rate . $itron_polly_tts_audio_location );

			$args     = array(
				'posts_per_page' => $batch_size,
				'post_type'      => $post_types_supported,
				// phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_query -- This admin-only bulk regeneration flow intentionally finds posts with stale audio settings.
				'meta_query'     => array(
					'relation' => 'OR',
					array(
						'key'     => 'itron_polly_tts_audio_link_location',
						'compare' => 'NOT EXISTS',
					),
					array(
						'key'     => 'itron_polly_tts_voice_id',
						'value'   => $itron_polly_tts_voice_id,
						'compare' => '!=',
					),
					array(
						'key'     => 'itron_polly_tts_sample_rate',
						'value'   => $itron_polly_tts_sample_rate,
						'compare' => '!=',
					),
					array(
						'key'     => 'itron_polly_tts_audio_location',
						'value'   => $itron_polly_tts_audio_location,
						'compare' => '!=',
					),
				),
			);
			$query    = new \WP_Query( $args );
			$post_ids = wp_list_pluck( $query->posts, 'ID' );

			if ( is_array( $post_ids ) && ! empty( $post_ids ) ) {
				foreach ( $post_ids as $post_id ) {
					try {
						if ( ! $common->has_post_audio( (int) $post_id ) ) {
							$common->set_post_audio_state( (int) $post_id, Common::AUDIO_STATE_RUNNING );
						}

						$clean_text    = $common->clean_text( $post_id, true, false );
						$sentences     = $common->break_text( $clean_text );
						$wp_filesystem = $common->prepare_wp_filesystem();
						$this->convert_to_audio( $post_id, $itron_polly_tts_sample_rate, $itron_polly_tts_voice_id, $sentences, $wp_filesystem, '' );
						$common->set_post_audio_state( (int) $post_id, Common::AUDIO_STATE_READY );
					} catch ( \Throwable $e ) {
						if ( ! $common->has_post_audio( (int) $post_id ) ) {
							$common->set_post_audio_state( (int) $post_id, Common::AUDIO_STATE_ERROR );
						}

						$logger->log(
							sprintf(
								'%s Error while bulk synthesizing post ( id=%s ): %s',
								__METHOD__,
								$post_id,
								$e->getMessage()
							)
						);
					}
				}
			} else {
				$step = 'done';
			}

			$percentage = $this->get_percentage_complete();
			echo wp_json_encode(
				array(
					'step'       => $step,
					'percentage' => $percentage,
				)
			);
		wp_die();
	}

	/**
	 * Calculate the percentage complete.
	 *
	 * @since      0.1
	 */
	private function get_percentage_complete() {
		$total_posts               = 0;
		$common                    = $this->common;
		$post_types_supported      = $common->get_posttypes_array();
		$posts_needing_translation = $this->get_num_posts_needing_transcription();

		foreach ( $post_types_supported as $post_type ) {
			$post_type_count = wp_count_posts( $post_type )->publish;
			$total_posts    += $post_type_count;
		}

		if ( 0 >= $total_posts || 0 >= $posts_needing_translation ) {
			$percentage = 100;
		} else {
			$percentage = round( $posts_needing_translation / $total_posts * 100, 2 );
		}

		return $percentage;
	}


	/**
	 * Checks how many posts should be converted.
	 *
	 * @since      0.1
	 */
	public function get_num_posts_needing_transcription() {

		$common                      = $this->common;
		$post_types_supported        = $common->get_posttypes_array();
		$itron_polly_tts_voice_id       = $common->get_voice_id();
		$itron_polly_tts_sample_rate    = $common->get_sample_rate();
		$itron_polly_tts_audio_location = ( 'on' === get_option( 'itron_polly_tts_s3' ) ) ? 's3' : 'local';

			$args  = array(
				'posts_per_page' => '-1',
				'post_type'      => $post_types_supported,
				// phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_query -- This admin-only progress counter intentionally counts posts matching the synthesis criteria.
				'meta_query'     => array(
					'relation' => 'AND',
					array(
						'key'     => 'itron_polly_tts_audio_link_location',
						'compare' => 'EXISTS',
					),
					array(
						'key'     => 'itron_polly_tts_voice_id',
						'value'   => $itron_polly_tts_voice_id,
						'compare' => '=',
					),
					array(
						'key'     => 'itron_polly_tts_sample_rate',
						'value'   => $itron_polly_tts_sample_rate,
						'compare' => '=',
					),
					array(
						'key'     => 'itron_polly_tts_audio_location',
						'value'   => $itron_polly_tts_audio_location,
						'compare' => '=',
					),
				),
			);
			$query = new \WP_Query( $args );
			return count( $query->posts );
	}


}
